[build]
  base = "web/"
  command = "npm run build"
  publish = "web/public"
  
[[redirects]]
  from = "/studio"
  to = "https://fluid.sanity.studio/desk"
  
[[headers]]
  for = "/path/to/serviceworker.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"
