[build]
  base = "web/"
  command = "npm run build"
  publish = "web/public"

 [[redirects]]
  from = "https://fluidpicturesinc.com/*"
  to = "https://www.fluidpicturesinc.com/:splat 301!"

[[redirects]]
  from = "https://fluidpictures.netlify.com/*"
  to = "https://fluidpictures.netlify.com/:splat 301!"
 
[[redirects]]
  from = "https://studio.fluidpicturesinc.com/"
  to = "https://fluid.sanity.studio/desk"

[[redirects]]
  from = "/studio"
  to = "https://fluid.sanity.studio/desk"

[[redirects]]
  from = "/contact-us"
  to = "/contact"

[[redirects]]
  from = "/credits-and-awards"
  to = "/about"

[[redirects]]
  from = "/services"
  to = "/equipment"

[[redirects]]
  from = "/furio-dolly-rail-cam/*"
  to = "/equipment/furio-dolly-rail-cam/:splat"

[[redirects]]
  from = "/towercam/*"
  to = "/equipment/towercam/:splat"

[[redirects]]
  from = "/jimmy-jib-triangle/*"
  to = "/equipment/jimmy-jib-triangle/:splat"

[[redirects]]
  from = "/remote-head/*"
  to = "/equipment/remote-head/:splat"

[[redirects]]
  from = "/steadicam/master-series-broadcast"
  to = "/equipment/steadicam/"

[[redirects]]
  from = "/steadicam/*"
  to = "/equipment/steadicam/:splat"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    cache-control = "max-age=0, must-revalidate, public"

